apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-enabled-aardvark
    devEnvApprovers:
    - lodotek
    environmentGitOwner: lodotek
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "804354894486"
    project: argocd-poc-356920
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: lodotek
    repository: jx3-gke-vault
  - key: staging
  - key: production
  ingress:
    domain: 34.173.60.72.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    email: 2421856+lodotek@users.noreply.github.com
    username: jx-bot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-tf-jx-enabled-aardvark-6e91e88a10c6
  - name: reports
    url: gs://reports-tf-jx-enabled-aardvark-6e91e88a10c6
  - name: repository
    url: gs://repository-tf-jx-enabled-aardvark-6e91e88a10c6
  terraformVault: true
  vault:
    bucket: vault-tf-jx-enabled-aardvark-6e91e88a10c6
    key: crypto-key-tf-jx-enabled-aardvark-6e91e88a10c6
    keyring: keyring-tf-jx-enabled-aardvark-6e91e88a10c6
    name: tf-jx-enabled-aardvark
    serviceAccount: tf-jx-enabled-aardvark-vt
  webhook: lighthouse
