apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    clusterName: tf-jx-enabled-aardvark
    devEnvApprovers:
    - lodotek
    environmentGitOwner: lodotek
    gitKind: github
    gitName: github
    gitServer: https://github.com/lodotek/jx3-gke-vault.git
    project: argocd-poc-356920
    provider: gke
    registry: gcr.io
  environments:
  - key: dev
    owner: lodotek
    repository: jx3-gke-vault
  - key: staging
  - key: production
  ingress:
    domain: ""
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
